__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


output_dir: ./output/rtdetrv2_r18vd_p2_p3_p4_120e_coco


PResNet:
  depth: 18
  freeze_at: -1
  freeze_norm: False
  pretrained: True
  return_idx: [0, 1, 2]


HybridEncoder:
  in_channels: [64, 128, 256]
  feat_strides: [4, 8, 16]
  hidden_dim: 256
  use_encoder_idx: [2]
  expansion: 0.5


RTDETRTransformerv2:
  feat_channels: [256, 256, 256]
  feat_strides: [4, 8, 16]
  num_levels: 3
  num_points: [4, 4, 4]
  num_layers: 3


epoches: 120

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.


train_dataloader:
  dataset:
    transforms:
      policy:
        epoch: 117
  collate_fn:
    scales: ~
